# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simp_lin_cpp <- function(y, x) {
    .Call(`_Simplin_simp_lin_cpp`, y, x)
}

